name: Automated Practice Accountability System

on:
  schedule:
    - cron: '0 22 * * *'  # Executes daily at 10:00 PM UTC
  workflow_dispatch:  # Manual trigger for testing and demonstration purposes

jobs:
  practice-accountability-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  

      - name: Configure Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Required Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz requests

      - name: Analyze Practice Submission Status
        id: submission_analysis
        run: |
          # Configure timezone for accurate date tracking (customize as needed)
          DATE=$(TZ=America/New_York date +"%Y-%m-%d")
          
          # Perform commit activity analysis for the practice period
          if git log --since="1 day ago" --author="$(git config --get user.email)" | grep -q ""; then
            echo "submission_status=completed" >> $GITHUB_ENV
            echo "message_subject=SQL Practice Milestone Achieved: Daily Submission Confirmed" >> $GITHUB_ENV
            echo "message_content=Your daily SQL practice has been successfully logged. This consistent dedication to skill development demonstrates the discipline and commitment that technical employers value highly. Your practice streak continues to build a compelling portfolio of technical persistence." >> $GITHUB_ENV
          else
            echo "submission_status=pending" >> $GITHUB_ENV
            echo "message_subject=Action Required: SQL Practice Submission Pending" >> $GITHUB_ENV
            echo "message_content=Our automated monitoring system has detected that today's SQL practice submission is still pending. Consistent technical practice is a key differentiator when showcasing your skills to potential employers. Consider allocating time today to maintain your learning momentum and practice continuity." >> $GITHUB_ENV
          fi

      - name: Execute Accountability Communication
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ env.message_subject }}
          body: |
            Hello,
            
            ${{ env.message_content }}
            
            Repository: https://github.com/${{ github.repository }}
            
            This communication is generated by an automated CI/CD pipeline demonstrating advanced GitHub Actions workflow implementation for technical practice monitoring and accountability systems.
            
            Regards,
            SQL Practice Automation System
          from: SQL Practice Monitoring <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.EMAIL_RECIPIENT }}
          
      - name: Generate Accountability Metrics Report
        run: |
          mkdir -p accountability_metrics
          echo "# SQL Practice Accountability Report" > accountability_metrics/status_report.md
          echo "## Analysis Timestamp" >> accountability_metrics/status_report.md
          echo "* Generated: $(date)" >> accountability_metrics/status_report.md
          echo "## Practice Metrics" >> accountability_metrics/status_report.md
          echo "* Status: ${{ env.submission_status }}" >> accountability_metrics/status_report.md
          echo "* Communication: ${{ env.message_subject }}" >> accountability_metrics/status_report.md
          echo "## System Information" >> accountability_metrics/status_report.md
          echo "* Workflow: Automated Practice Accountability System" >> accountability_metrics/status_report.md
          echo "* Repository: ${{ github.repository }}" >> accountability_metrics/status_report.md
          
      - name: Archive Accountability Metrics
        uses: actions/upload-artifact@v4
        with:
          name: practice-accountability-metrics
          path: accountability_metrics/status_report.md
          retention-days: 90
