name: Debug Email Configuration

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.SMTP_USERNAME }}" ]; then
            echo "SMTP_USERNAME exists and is not empty"
          else
            echo "SMTP_USERNAME is missing or empty"
          fi
          
          if [ -n "${{ secrets.EMAIL_RECIPIENT }}" ]; then
            echo "EMAIL_RECIPIENT exists and is not empty"
          else
            echo "EMAIL_RECIPIENT is missing or empty"
          fi
      
      - name: Debug email recipient
        run: |
          # This will print the first character of your email recipient to verify it exists
          # without exposing your full email address
          if [ -n "${{ secrets.EMAIL_RECIPIENT }}" ]; then
            echo "First character of EMAIL_RECIPIENT: ${${{ secrets.EMAIL_RECIPIENT }}:0:1}"
            echo "Length of EMAIL_RECIPIENT: ${#${{ secrets.EMAIL_RECIPIENT }}}"
          fi
      
      - name: Try sending email with hardcoded recipient
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Debug Test Email
          body: This is a debug test email
          from: Debug Test <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.SMTP_USERNAME }}  # Send to yourself as a test
