name: SQL Practice Activity Tracker

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 AM UTC daily, which is 10 PM CST
  workflow_dispatch:  # Manual trigger for testing

jobs:
  track-practice-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 30  # Get last 30 days of history

      - name: Pull latest changes
        run: git pull origin main

      - name: Analyze Practice Activity
        id: activity_analysis
        run: |
          # Get today's date
          TODAY=$(date +"%Y-%m-%d")
          echo "today=$TODAY" >> $GITHUB_OUTPUT
          
          # Check if there are any commits for today
          if git log --since="1 day ago" --author="$(git config --get user.email)" | grep -q ""; then
            echo "status=completed" >> $GITHUB_OUTPUT
            echo "message=✅ Practice completed" >> $GITHUB_OUTPUT
          else
            echo "status=pending" >> $GITHUB_OUTPUT
            echo "message=⚠️ Practice pending" >> $GITHUB_OUTPUT
          fi
          
          # Calculate streak by counting days with commits in the last 30 days
          STREAK_DATA=$(git log --since="30 days ago" --author="$(git config --get user.email)" --date=short --pretty=format:"%ad" | sort | uniq)
          STREAK_COUNT=$(echo "$STREAK_DATA" | wc -l)
          echo "streak=$STREAK_COUNT" >> $GITHUB_OUTPUT
          
          # Get last 7 days activity for a mini report
          LAST_WEEK=$(git log --since="7 days ago" --author="$(git config --get user.email)" --date=short --pretty=format:"%ad" | sort | uniq)
          echo "last_week<<EOF" >> $GITHUB_OUTPUT
          echo "$LAST_WEEK" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate Activity Badge
        run: |
          mkdir -p .github/badges
          
          # Create practice status badge
          cat > .github/badges/practice-status.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="180" height="20">
            <linearGradient id="b" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <mask id="a">
              <rect width="180" height="20" rx="3" fill="#fff"/>
            </mask>
            <g mask="url(#a)">
              <path fill="#555" d="M0 0h103v20H0z"/>
              <path fill="${{ steps.activity_analysis.outputs.status == 'completed' && '4c1' || 'dfb317' }}" d="M103 0h77v20H103z"/>
              <path fill="url(#b)" d="M0 0h180v20H0z"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
              <text x="51.5" y="15" fill="#010101" fill-opacity=".3">Practice Status</text>
              <text x="51.5" y="14">Practice Status</text>
              <text x="140.5" y="15" fill="#010101" fill-opacity=".3">${{ steps.activity_analysis.outputs.message }}</text>
              <text x="140.5" y="14">${{ steps.activity_analysis.outputs.message }}</text>
            </g>
          </svg>
          EOF
          
          # Create streak badge
          cat > .github/badges/practice-streak.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="170" height="20">
            <linearGradient id="b" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <mask id="a">
              <rect width="170" height="20" rx="3" fill="#fff"/>
            </mask>
            <g mask="url(#a)">
              <path fill="#555" d="M0 0h120v20H0z"/>
              <path fill="#007ec6" d="M120 0h50v20H120z"/>
              <path fill="url(#b)" d="M0 0h170v20H0z"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
              <text x="60" y="15" fill="#010101" fill-opacity=".3">Practice Streak</text>
              <text x="60" y="14">Practice Streak</text>
              <text x="144" y="15" fill="#010101" fill-opacity=".3">${{ steps.activity_analysis.outputs.streak }} days</text>
              <text x="144" y="14">${{ steps.activity_analysis.outputs.streak }} days</text>
            </g>
          </svg>
          EOF

      - name: Generate Activity Report
        run: |
          cat > ACTIVITY_REPORT.md << EOF
          # SQL Practice Activity Report
          
          Last updated: ${{ steps.activity_analysis.outputs.today }}
          
          ## Current Status
          
          ${{ steps.activity_analysis.outputs.message }}
          
          ## Practice Streak
          
          **Current streak:** ${{ steps.activity_analysis.outputs.streak }} days
          
          ## Recent Activity
          
          Days with practice in the last week:
          
          \`\`\`
          ${{ steps.activity_analysis.outputs.last_week }}
          \`\`\`
          
          *This report is automatically generated by GitHub Actions to track daily SQL practice activity.*
          EOF

      - name: Update README with Badges
        run: |
          # Check if README exists
          if [ ! -f README.md ]; then
            echo "# SQL Daily Practice" > README.md
          fi
          
          # Update or add badge section
          if grep -q "<!-- PRACTICE-BADGES:START -->" README.md; then
            # Update existing badges
            sed -i '/<!-- PRACTICE-BADGES:START -->/,/<!-- PRACTICE-BADGES:END -->/c\<!-- PRACTICE-BADGES:START -->\n![Practice Status](https://github.com/${{ github.repository }}/blob/main/.github/badges/practice-status.svg)\n![Practice Streak](https://github.com/${{ github.repository }}/blob/main/.github/badges/practice-streak.svg)\n<!-- PRACTICE-BADGES:END -->' README.md
          else
            # Add badges section
            sed -i '1a <!-- PRACTICE-BADGES:START -->\n![Practice Status](https://github.com/${{ github.repository }}/blob/main/.github/badges/practice-status.svg)\n![Practice Streak](https://github.com/${{ github.repository }}/blob/main/.github/badges/practice-streak.svg)\n<!-- PRACTICE-BADGES:END -->' README.md
          fi
          
          # Add automation section if it doesn't exist
          if ! grep -q "## Automation Features" README.md; then
            cat >> README.md << EOF
          
          ## Automation Features
          
          This repository demonstrates GitHub Actions automation for tracking practice activity:
          
          - **Automated Status Tracking**: Daily checks for SQL practice submissions
          - **Visual Status Badges**: Dynamic SVG badges showing current status and streak
          - **Activity Reports**: Automatically generated reports of practice patterns
          - **Continuous Integration**: GitHub Actions workflow demonstrating CI/CD skills
          
          Check out the [Activity Report](ACTIVITY_REPORT.md) for current statistics.
          EOF
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/ README.md ACTIVITY_REPORT.md
          git commit -m "Update practice activity status: ${{ steps.activity_analysis.outputs.message }}" || echo "No changes to commit"
          git push