name: Test Email

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Test Email - GitHub Actions
          body: This is a test email from GitHub Actions
          from: SQL Practice Monitoring <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.EMAIL_RECIPIENT }}