name: Debug Email Configuration

on:
  workflow_dispatch:  # Only manual trigger

jobs:
  debug-email-job:  # Unique job name
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          if [ -n "${{ secrets.SMTP_USERNAME }}" ]; then
            echo "SMTP_USERNAME exists and is not empty"
          else
            echo "SMTP_USERNAME is missing or empty"
          fi
          
          if [ -n "${{ secrets.EMAIL_RECIPIENT }}" ]; then
            echo "EMAIL_RECIPIENT exists and is not empty"
          else
            echo "EMAIL_RECIPIENT is missing or empty"
          fi
      
      - name: Simple Email Test
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Debug Test Email
          body: This is a debug test email
          from: Debug Test <${{ secrets.SMTP_USERNAME }}>
          to: ${{ secrets.EMAIL_RECIPIENT }}