name: Practice Status Notification

on:
  schedule:
    - cron: '0 18 * * *'  # Daily at 6 PM UTC
  workflow_dispatch:

jobs:
  practice-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Check for recent submissions
        id: check-submissions
        run: |
          if git log --since="1 day ago" --author="$(git config --get user.email)" | grep -q ""; then
            echo "status=completed" >> $GITHUB_ENV
            echo "message=Great job! You've completed your practice today." >> $GITHUB_ENV
          else
            echo "status=pending" >> $GITHUB_ENV
            echo "message=Reminder: You haven't completed your practice today." >> $GITHUB_ENV
          fi
          
      - name: Generate Notification Report
        run: |
          mkdir -p notifications
          echo "# Practice Status: ${{ env.status }}" > notifications/status.md
          echo "" >> notifications/status.md
          echo "${{ env.message }}" >> notifications/status.md
          echo "" >> notifications/status.md
          echo "Generated: $(date)" >> notifications/status.md
          
      - name: Upload Notification Report
        uses: actions/upload-artifact@v4
        with:
          name: practice-status-notification
          path: notifications/status.md
          retention-days: 30
