name: Direct Email Test

on:
  workflow_dispatch:

jobs:
  direct-email-test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Email With Direct Address
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Direct Test Email
          body: This is a direct test email
          from: Direct Test <${{ secrets.SMTP_USERNAME }}>
          to: benkaanata@gmail.com
