name: "Verify Daily Practice Content"

on:
  # Manual trigger available for testing; later you can add a scheduled cron event.
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  verify-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Content Verification Script
        run: python scripts/verify_daily_practice_content.py

      - name: Upload Verification Results
        # Always upload results, regardless of the script outcome.
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: content-verification-results
          path: website/content-verification-results-*.md
